# Generated by Django 3.2.11 on 2023-04-24 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseaselocatorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctorprofile',
            new_name='doctor',
        ),
        migrations.RenameModel(
            old_name='Patientprofile',
            new_name='patient',
        ),
    ]
